import type { SqliteTruthKernelStorage } from '../jarvis_fusion/truth-kernel/storage.js';

export function exportAgentsMd(store: SqliteTruthKernelStorage): string {
  const decisions = store.listActiveDecisions(50);
  const preferences = store.listActivePreferences(50);
  const entities = store.listActiveEntities(50);

  const lines: string[] = [
    '# AGENTS.md (auto-generated by Waypath)',
    '',
    '## Coding Rules (from decisions)',
  ];

  if (decisions.length === 0) {
    lines.push('_(none)_');
  } else {
    for (const d of decisions) {
      lines.push(`- ${d.title} — ${d.statement}`);
    }
  }

  lines.push('', '## Style Preferences');
  if (preferences.length === 0) {
    lines.push('_(none)_');
  } else {
    for (const p of preferences) {
      lines.push(`- ${p.key}: ${p.value} (${p.strength})`);
    }
  }

  lines.push('', '## Project Context');
  if (entities.length === 0) {
    lines.push('_(none)_');
  } else {
    for (const e of entities) {
      lines.push(`- ${e.name} (${e.entity_type}): ${e.summary}`);
    }
  }

  return lines.join('\n');
}
