import { createTruthKernelStorage, ensureTruthKernelSeedData } from '../../src/jarvis_fusion/truth-kernel/index.js';
import { exportClaudeMd, exportAgentsMd } from '../../src/export/index.js';
import { assert } from '../../src/shared/assert';

function nowIso(): string {
  return new Date().toISOString();
}

function createSeededStore() {
  const store = createTruthKernelStorage(':memory:');
  ensureTruthKernelSeedData(store, { project: 'alpha', objective: 'build v1', activeTask: 'implement' });

  const ts = nowIso();
  store.upsertEntity({ entity_id: 'tool:sqlite', entity_type: 'tool', name: 'SQLite', summary: 'Local-first embedded database engine', state_json: '{}', status: 'active', canonical_page_id: null, created_at: ts, updated_at: ts });
  store.upsertDecision({ decision_id: 'decision:use-sqlite', title: 'Use SQLite for truth kernel', statement: 'SQLite chosen for local-first zero-dependency persistence.', status: 'active', scope_entity_id: 'project:alpha', effective_at: ts, superseded_by: null, provenance_id: null, created_at: ts, updated_at: ts });
  store.upsertPreference({ preference_id: 'pref:language', subject_kind: 'workspace', subject_ref: null, key: 'language', value: 'korean', strength: 'strong', status: 'active', provenance_id: null, created_at: ts, updated_at: ts });

  return store;
}

export function testExportClaudeMdContainsHeader(): void {
  const store = createSeededStore();
  try {
    const output = exportClaudeMd(store);
    assert(output.includes('# Project Context (auto-generated by Waypath)'), 'Expected claude-md header');
    assert(typeof output === 'string', 'Output should be string');
  } finally {
    store.close();
  }
}

export function testExportClaudeMdContainsDecisions(): void {
  const store = createSeededStore();
  try {
    const output = exportClaudeMd(store);
    assert(output.includes('## Active Decisions'), 'Expected Active Decisions section');
    assert(output.includes('Use SQLite for truth kernel'), 'Expected decision title in output');
  } finally {
    store.close();
  }
}

export function testExportClaudeMdContainsPreferences(): void {
  const store = createSeededStore();
  try {
    const output = exportClaudeMd(store);
    assert(output.includes('## Preferences'), 'Expected Preferences section');
    assert(output.includes('language=korean'), 'Expected preference key=value in output');
  } finally {
    store.close();
  }
}

export function testExportClaudeMdContainsEntities(): void {
  const store = createSeededStore();
  try {
    const output = exportClaudeMd(store);
    assert(output.includes('## Key Entities'), 'Expected Key Entities section');
    assert(output.includes('SQLite'), 'Expected entity name in output');
  } finally {
    store.close();
  }
}

export function testExportAgentsMdContainsHeader(): void {
  const store = createSeededStore();
  try {
    const output = exportAgentsMd(store);
    assert(output.includes('# AGENTS.md (auto-generated by Waypath)'), 'Expected agents-md header');
  } finally {
    store.close();
  }
}

export function testExportAgentsMdContainsCodingRules(): void {
  const store = createSeededStore();
  try {
    const output = exportAgentsMd(store);
    assert(output.includes('## Coding Rules (from decisions)'), 'Expected Coding Rules section');
    assert(output.includes('Use SQLite for truth kernel'), 'Expected decision title in output');
  } finally {
    store.close();
  }
}

export function testExportEmptyStoreReturnsValidMarkdown(): void {
  const store = createTruthKernelStorage(':memory:');
  try {
    const claudeMd = exportClaudeMd(store);
    assert(claudeMd.includes('# Project Context'), 'Empty store: claude-md should still have header');
    assert(claudeMd.includes('_(none)_'), 'Empty store: should show (none) placeholders');

    const agentsMd = exportAgentsMd(store);
    assert(agentsMd.includes('# AGENTS.md'), 'Empty store: agents-md should still have header');
    assert(agentsMd.includes('_(none)_'), 'Empty store: should show (none) placeholders');
  } finally {
    store.close();
  }
}
